routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index');
Route::get('/profile/{user_id}', 'HomeController@show');
Route::post('/profile/hidden', array('as' => 'profile.hidden', 'uses' => 'HomeController@hidden'));

Auth::routes();

Route::group(['middleware' => 'auth'], function () {
    Route::get('/entry/get_data', array('as' => 'entry.get_data', 'uses' => 'EntryController@getData'));
    Route::resource('entry', 'EntryController');
});

app/Models/Entry.php
<?php

namespace App\Models;


use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;

class Entry extends Model
{

    protected $fillable = ['title', 'content', 'user_id'];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function user()
    {
        return $this->belongsTo('App\Models\User', 'user_id', 'id');
    }

    /**
     * @param User $user
     * @param bool $limit
     * @return \Illuminate\Database\Eloquent\Collection|static[]
     */
    public function firstRows(User $user, $limit = true)
    {
        $query = $this->where('user_id', $user->id)->orderBy('created_at', 'DESC');
        if ($limit) {
            $query->limit(env('LIMIT', 3));
        }
        $query->with('user');
        return $query->get();
    }

}

app/Http/Controllers/EntryController.php
<?php

namespace App\Http\Controllers;


use App\Models\Entry;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Yajra\Datatables\Datatables;

class EntryController extends Controller
{

    private $entry;

    /**
     * EntriesController constructor.
     *
     * @param Entry $entry
     */
    public function __construct(Entry $entry)
    {
        $this->entry = $entry;
    }

    /**
     * @return mixed
     */
    public function getData()
    {
        $entries = Entry::select([
            'entries.id',
            'entries.title',
            'entries.content',
            'entries.created_at',
        ])->where('entries.user_id', Auth::user()->id);

        return Datatables::of($entries)->make(true);
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        return redirect('/');
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        return view('app.entry.create');
    }

    /**
     * @param Request $request
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request)
    {
        $this->entry->create([
            'title'   => $request->get('title'),
            'content' => $request->get('content'),
            'user_id' => Auth::user()->id,
        ]);

        return redirect('profile/'.Auth::user()->id)
            ->with('success', 'Success', ['entity' => 'Post']);
    }

    /**
     * @param Entry $entry
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function show(Entry $entry)
    {
        return view('app.entry.show', compact('entry'));
    }


    /**
     * @param Entry $entry
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit(Entry $entry)
    {
        return view('app.entry.edit', compact('entry'));
    }

    /**
     * @param Request $request
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Request $request)
    {
        $post = $this->entry->find($request->get('id'));
        $post->fill($request->all());
        $post->save();

        return redirect('profile/'.Auth::user()->id)
            ->with('success', 'Success', ['entity' => 'Post']);
    }

}

resources/views/app/entry/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="widget">
                <div class="widget-head text-center">
                    <div class="pull-left">Create Post</div>
                    <div class="clearfix"></div>
                </div>
                <div class="widget-content">
                    <div class="padd">
                        {!! Form::open(['url' => '/entry']) !!}
                        <div class="form-group">
                            <div class="row">
                                <div class="col-md-12">
                                    {!! Form::label('title', 'Title') !!}
                                    {!! Form::text('title', '', ['class' => 'form-control', 'required']) !!}
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="row">
                                <div class="col-md-12">
                                    {!! Form::label('content', 'Content') !!}
                                    {!! Form::textarea('content', '', ['class' => 'form-control', 'required']) !!}
                                </div>
                            </div>
                        </div>
                        {!! Form::submit('Post', ['class' => 'btn btn-primary']) !!}
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/app/entry/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="widget">
                <div class="widget-head text-center">
                    <div class="pull-left">Edit Post</div>
                    <div class="clearfix"></div>
                </div>
                <div class="widget-content">
                    <div class="padd">
                        {!! Form::open(['url' => '/entry/'.$entry->id, 'method' => 'PUT']) !!}
                        {!! Form::hidden('id', $entry->id) !!}
                        <div class="form-group">
                            <div class="row">
                                <div class="col-md-12">
                                    {!! Form::label('title', 'Title') !!}
                                    {!! Form::text('title', $entry->title, ['class' => 'form-control', 'required']) !!}
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="row">
                                <div class="col-md-12">
                                    {!! Form::label('content', 'Content') !!}
                                    {!! Form::textarea('content', $entry->content, ['class' => 'form-control', 'required']) !!}
                                </div>
                            </div>
                        </div>
                        {!! Form::submit('Edit', ['class' => 'btn btn-primary']) !!}
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/app/entry/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="row" ng-app="challengeApp">
        <div class="col-lg-12" ng-controller="EntriesGrid">
            <div class="widget" challenge-app-data-table="dataTableOptions">
                <div class="widget-head text-center">
                    <div class="pull-left">List Posts</div>
                    <div class="clearfix"></div>
                    <div class="clearfix"></div>
                </div>
                <div class="widget-content">
                    <div class="padd">
                        <table class="table table-striped bootstrap-datatable datatable">
                            <thead>
                            <tr>
                                <th>Id</th>
                                <th>Title</th>
                                <th>Content</th>
                                <th>Created At</th>
                                <th>Actions</th>
                            </tr>
                            </thead>
                            <tbody></tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/app/entry/show.blade.php
@extends('layouts.app')
@section('content')
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="widget">
                <div class="widget-head text-center">
                    <div class="pull-left">Show Post</div>
                    <div class="clearfix"></div>
                </div>
                <div class="widget-content">
                    <div class="padd">
                        <div class="form-group">
                            <div class="row">
                                <div class="col-md-12">
                                    {!! Form::label('title', 'Title') !!}
                                    <p>{!! $entry->title !!}</p>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="row">
                                <div class="col-md-12">
                                    {!! Form::label('content', 'Content') !!}
                                    <p>{!! $entry->content !!}</p>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="row">
                                <div class="col-md-12">
                                    {!! Form::label('created_at', 'Created At') !!}
                                    <p>{!! $entry->created_at !!}</p>
                                </div>
                            </div>
                        </div>
                        {!! link_to_route('entry.index', 'Cancel', [], ['class' => 'btn'])  !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection